name             "boost"
maintainer       "Chef Software, Inc."
maintainer_email "cookbooks@chef.io"
license          "Apache 2.0"
description      "Installs libboost"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.3.0"
name             "boost"
provides         "boost"
recipe           "boost", "Installs libboost-dev"
recipe           "boost::source", "Installs boost via source tarbal compile."

depends          "apt"
depends          "build-essential"

supports "ubuntu"
supports "debian"
supports "centos"
supports "amazon"
supports "scientific"
supports "fedora"
supports "redhat"
supports "oracle"
